events {
    worker_connections 1024;
}

http {
    upstream api_backend {
        least_conn;
        server api1:8080;
        server api2:8080;
        server api3:8080;
    }

    upstream webapp_backend {
        least_conn;
        server webapp1:80;
        server webapp2:80;
        server webapp3:80;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
        }

        location /node-info {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://webapp_backend;
            proxy_set_header Host $host;
        }
    }
}